"""
Ethara Seat Allocation & Project Mapping System — FastAPI Entry Point.

Architecture:
  - Routers are registered with their prefixes here.
  - CORS is configured to allow the React frontend.
  - Database tables are created on startup (dev mode).
  - Rate limiting via slowapi (Fixed Window Counter, per-IP).
  - /docs → Swagger UI (auto-generated by FastAPI).
  - /redoc → ReDoc UI.
"""
from contextlib import asynccontextmanager
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from slowapi import _rate_limit_exceeded_handler
from slowapi.errors import RateLimitExceeded
from slowapi.middleware import SlowAPIMiddleware

from .config import get_settings
from .database import create_tables
from .limiter import limiter
from .routers import (
    employees_router,
    projects_router,
    seats_router,
    dashboard_router,
    ai_router,
    seed_router,
    auth_router,
)

settings = get_settings()


@asynccontextmanager
async def lifespan(app: FastAPI):
    """Create DB tables on startup."""
    create_tables()
    yield


app = FastAPI(
    title=settings.APP_TITLE,
    version=settings.APP_VERSION,
    description=settings.APP_DESCRIPTION,
    docs_url="/docs",
    redoc_url="/redoc",
    openapi_url="/openapi.json",
    lifespan=lifespan,
)

# ── Rate limiter wiring (Open/Closed — extend by adding new limits, not editing) ─
app.state.limiter = limiter
app.add_exception_handler(RateLimitExceeded, _rate_limit_exceeded_handler)
app.add_middleware(SlowAPIMiddleware)

# ── CORS ──────────────────────────────────────────────────────────────────────
app.add_middleware(
    CORSMiddleware,
    allow_origins=settings.ALLOWED_ORIGINS,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# ── Routers ───────────────────────────────────────────────────────────────────
app.include_router(auth_router)
app.include_router(employees_router)
app.include_router(projects_router)
app.include_router(seats_router)
app.include_router(dashboard_router)
app.include_router(ai_router)
app.include_router(seed_router)


# ── Health check ──────────────────────────────────────────────────────────────
@app.get("/health", tags=["Health"])
def health_check():
    return {"status": "healthy", "version": settings.APP_VERSION}


@app.get("/", tags=["Health"])
def root():
    return {
        "message": "Ethara Seat Allocation API",
        "docs": "/docs",
        "version": settings.APP_VERSION,
    }
